[ -z "$PS1" ] && return

if [ "$PS1" ]; then
    complete -cf sudo
fi

shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s checkwinsize

export LC_NUMERIC="POSIX"
export PAGER=less
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

export GPG_TTY=$(tty)

eval ~/env/env.sh
