[ -z "$PS1" ] && return

if [ "$PS1" ]; then
    complete -cf sudo
fi

shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s checkwinsize

export LC_NUMERIC="POSIX"
export PAGER=less
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

export GPG_TTY=$(tty)

[ -f "$HOME/.profile" ] && . "$HOME/.profile"

. "$HOME/snap/code/197/.local/share/../bin/env"

export PATH="$HOME/.npm-global/bin:$PATH"

# Added by LM Studio CLI (lms)
#export PATH="$PATH:/Users/roarc/.lmstudio/bin"
# End of LM Studio CLI section


alias claude-mem='bun "/Users/roarc/.claude/plugins/marketplaces/thedotmack/plugin/scripts/worker-service.cjs"'
