#!/usr/bin/env zsh
# macOS: Set minimal PATH early for zsh initialization
case "$OSTYPE" in
  darwin*)
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
    ;;
esac

[ -f "$HOME/.profile" ] && source "$HOME/.profile"

[ -f "$HOME/.local/cargo/env" ] && source "$HOME/.local/cargo/env"
