# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME_RANDOM_CANDIDATES=( "fino" "rkj" "bria" )

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
export UPDATE_ZSH_DAYS=7

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

plugins=(aliases systemd git git-extras gitignore ssh colorize docker docker-compose podman kubectl minikube golang rust npm sudo zsh-syntax-highlighting zsh-completions zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

#zsh-completions
fpath=(~/.oh-my-zsh/plugins/zsh-completions/src $fpath)

#zsh-autosuggest
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#cc00cc"
bindkey '^ ' autosuggest-accept # ctrl+space

export GPG_TTY=$(tty)

source ~/env/env.sh

source <(fzf --zsh)
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVESIZE=10000
setopt appendhistory

# bun completions
[ -s "/home/roarc/.bun/_bun" ] && source "/home/roarc/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
