#!/bin/sh

disk_usage() {
  df / | awk '/dev/ {print $5}'| tr -d "%"
}

cpu_usage() {
    vmstat  | awk '/[0-9]/ { print $13 }'
}

cpu_temperature() {
    temp=$(cat /sys/class/thermal/thermal_zone1/temp)
    echo "scale=0; $temp/1000" | bc
}

mem_usage() {
    free  | awk '/Mem/ { printf int($2 / $3) }'
}

fmt_yambar_range() {
    name="$1"
    val="$2"
    echo "$name|range:0-100|$val"
}

# https://manpages.debian.org/unstable/yambar/yambar-modules-script.5.en.html

fmt_yambar_range cpu  "$(cpu_usage)"
fmt_yambar_range mem  "$(mem_usage)"
fmt_yambar_range disk "$(disk_usage)"
echo "cpu_temp|int|$(cpu_temperature)"
echo
