#!/bin/sh
. ${ENV_HOME}/.env
. ${ENV_HOME}/scripts/functions.sh

REMOTE="transmission-remote -n ${TRANSMISSION_AUTH}"

INCLMOV="$HOME/inc.txt"
MAXACTIVE="8"

substr() {
    if [[ $1 == *"$2"* ]]; then
        return 1
    fi
    return 0
}

tmove() {
    while read p; do
        echo $p
        substr $1 $p
    done <$INCLMOV
}

LIST="$($REMOTE -l | tail --lines=+2 | grep 100% | grep -v Stopped | awk '{ print $1; }')"
for ID in $LIST; do
    NAME="$($REMOTE --torrent $ID --info | grep Name:)"
    einfo ">>> $ID: ${NAME#*Name: }"
    ask "move to \"$DEST\""
    if [ $? == 0 ]; then
        $REMOTE --torrent $ID --move "$DEST" >/dev/null
    fi
    $REMOTE --torrent $ID --remove >/dev/null
done

# how many are still running?
ACTIVE="$($REMOTE -l | tail --lines=+2 | grep -v Stopped | grep -v "^Sum\:" | wc -l)"
if [ $ACTIVE -gt $MAXACTIVE ]; then
    exit
fi

# start new torrents
LIST="$($REMOTE -l | tail --lines=+2 | grep -v 100% | grep Stopped | shuf | head -n $(expr $MAXACTIVE - $ACTIVE) | awk '{ print $1; }')"
for ID in $LIST; do
    NAME="$($REMOTE --torrent $ID --info | grep Name:)"
    echo ">>> $ID: ${NAME#*Name: }"
    $REMOTE --torrent $ID --start --verify >/dev/null
done
