run: 
  concurrency: 12
linters-settings:
  wsl:
linters:
  enable-all: true
  disable:
    - tagalign
    - gofumpt
    - tagliatelle
    - depguard
    - gci
    - godot
    - nlreturn
    - wsl
    - testpackage
    - gomnd
    - mnd
    - lll
